version: 2
jobs:
  build:
    branches:
      only :
        - circleci
    working_directory: ~/okta.github.io
    docker:
      - image: circleci/ruby:2.6.2-node-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: install-bundler
          command: gem install bundler
      - run:
          name: install-npm
          command: npm install
      - run:
          name: install-gems
          command: bundle install
      - run:
          name: test
          command: ./scripts/travis.sh
      - run:
          name: install-aws-cli
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install awscli
      - deploy:
          name: deploy
          command: ./scripts/publish-s3.sh
