---
layout: blog_post
title: "Three Developer Tools I'm Thankful For"
author: mraible
description: "To celebrate Thanksgiving, here's a list of Matt Raible's favorite developer tools. Learn why he likes them and how they can help you."
tags: [holiday, developer, thanksgiving, tools]
tweets:
- "Matt Raible (@mraible) really likes IntelliJ IDEA, zsh, and Asciidoctor. What about you?"
- "What developer tools are you thankful for this Thanksgiving?"
---

I ❤️ Thanksgiving. It's one of my favorite holidays. I love it because it's a time of reflection and gratitude. As an open source developer, I have a lot to be thankful for. Many of the tools I use are created by developers from around the world, and I get to use them for free! 

I'm also very thankful for my awesome job at [@oktadev](https://twitter.com/oktadev). I get to write example apps with open source software, publish them as [open source projects](https://github.com/oktadeveloper), and help developers understand how to use Okta's [developer APIs](https://developer.okta.com/reference/).

If you've been a software developer for any length of time, you probably know what makes it fun: the opportunity to learn new stuff, to have an impact on the company's business, and to have a great boss. I'm _very_ thankful I have all three. Add to that my fantastic team (@rdegges, @leebrandt, @aaronpk, @reverentgeek, @LindsayB610, and @kaifubrent) &mdash; and I've got a metric shit-ton to be thankful for!

Enough of the "I have cool co-workers" talk, you're hear to find out about my favorite tools. 

## IntelliJ IDEA

[IntelliJ IDEA](https://www.jetbrains.com/idea/) is an Integrated Developer Environment (IDE), mostly known by Java developers. 

{% img blog/thankful-2018/idea.png alt:"IntelliJ IDEA" width:"600" %}{: .center-image }

The first languages I learned to program in were HTML, CSS, and JavaScript, way back in the mid-90s. I started learning Java in the late 90s. At that time, my favorite IDE was HomeSite. Back then, I used to write Java code and search/copy/paste the imports into my code. Such pain!

It wasn't until the early 2000s that I found an IDE that wasn't painful to use. I fell in love with Eclipse for a few years, back in the Struts 1.0/Spring 1.0 days. In the mid-2000s, I migrated my AppFuse project from using Ant to Maven and ended up moving to IDEA because its Maven support was so much better. Then I moved back to the area I love -- UI development -- and found that IDEA had excellent support for HTML, CSS, and JavaScript. I haven't looked back since.

In addition to plugins that support virtually every language, IDEA has a killer feature that I use in my demos: [Live Templates](https://www.jetbrains.com/help/idea/using-live-templates.html). Live templates allow you to record code snippets and recall them with a quick shortcut that you define. You can see them in action in my recent [Full Stack Reactive screencast](https://youtu.be/1xpwYe154Ys). 

## Oh My Zsh

[Oh My Zsh](https://ohmyz.sh/) is a favorite I've only recently added. I've used Bash for most of my career. I started using Zsh after watching [Sebastian Daschner](https://twitter.com/daschners) mention it in a talk on productivity at the 2017 Java Champions summit. It's been a little over a year since I started using it and I absolutely love it. I use its Git, Node, and [JHipster](https://www.jhipster.tech/oh-my-zsh/) plugins, along with the [command time plugin](https://github.com/popstas/zsh-command-time).

When it comes to shells, I also really dig [iTerm2](https://www.iterm2.com/). My favorite feature these days is Cmd+D and Cmd+Shift+D to split the terminal vertically and horizontally.

{% img blog/thankful-2018/iterm.png alt:"iTerm with Oh My Zsh" width:"600" %}{: .center-image }

## Asciidoctor

[Asciidoctor](https://asciidoctor.org/) is a text processor and publishing toolchain that converts AsciiDoc files into HTML5, PDF, EPUB, and MOBI. It probably support more formats, but these are the ones I use.

I really got into Asciidoctor a few years ago when I authored the first version of the [JHipster Mini-Book](https://www.infoq.com/minibooks/jhipster-mini-book) for InfoQ. When I first suggested the idea, they thought it'd be the most expensive book they'd ever produced, but they were still willing to let me do it. They thought it'd require taking the PDF generated from Asciidoctor, putting it into their design program, then manipulating it to output EPUB, MOBI, and a printable version too. In the end, it turned out to be the _cheapest_ book they'd ever produced! Asciidoctor supports all of the aforementioned outputs and I was able to match InfoQ's mini-book design with code and CSS. 

I enjoyed the process so much, I created a [template project for InfoQ mini-books](https://github.com/mraible/infoq-mini-book). Even if you're not writing an InfoQ mini-book, this template can help you self-publish your own book.

When I started writing on this blog (which uses Jekyll, soon to be Hugo), I reluctantly used Markdown to author posts. Fast forward to today, and we've integrated [AsiiDoc support](https://github.com/okta/okta.github.io/pull/2321)! I have to thank [Josh Long](https://twitter.com/starbuxman) for motivating this integration. He started writing our [Reactive Programming series](/blog/2018/09/21/reactive-programming-with-spring) with it. The code callouts were so cool, I had to make them work. Below is an example.

.Read data from a file _synchronously_
====
[source,java]
----
package com.example.io;

import lombok.extern.log4j.Log4j2;
import org.springframework.util.FileCopyUtils;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.function.Consumer;

@Log4j2
class Synchronous implements Reader {

    @Override
    public void read(File file, Consumer<BytesPayload> consumer) throws IOException {
        try (FileInputStream in = new FileInputStream(file)) { // <1>
            byte[] data = new byte[FileCopyUtils.BUFFER_SIZE];
            int res;
            while ((res = in.read(data, 0, data.length)) != -1) { // <2>
                    consumer.accept(BytesPayload.from(data, res)); // <3>
            }
        }
    }
}
----
<1> source the file using a regular `java.io.File`
<2> _pull_ the results out of the source one line at a time...
<3> I've written this code to accept a `Consumer<BytesPayload>` that gets called when there's new data
====

One downside to AsciiDoc is GitHub doesn't support it as well as Markdown. You can fix that by viewing your ``*.adoc` files through DocGist, as I've done with my [Angular 7 Tutorial](http://gist.asciidoctor.org/?github-mraible/ng-demo//README.adoc).

## Honorable Mentions

We try to limit our Thanksgiving "favorite developer tools" posts to three, but I can't help but mention two other ones I use almost daily.

* [HTTPie](http://httpie.org): If you like cURL, you're going to _love_ HTTPie.
* [Lighthouse](https://developers.google.com/web/tools/lighthouse/): a website testing tool that's invaluable when developing PWAs, and optimizing your app UIs.

## Happy Thanksgiving!

{% img blog/thankful/turkey.png alt:"turkey" width:"600" %}{: .center-image }

It was fun taking some time to write about my favorite three developer tools. If you have some favorite tools, we'd love to hear about them. Sharing is caring! 😊

If you don't live in the US, and therefore don't celebrate Thanksgiving, I invite you to take some time today and look around. Be thankful for what you have and the people around you.

I hope you have an awesome Thanksgiving.

&mdash; Matt
