---
layout: blog_post
title: "10 Myths About Java in 2019"
author: mraible
description: ""
tags: [java]
tweets:
-
-
-
---

Java turned 24 years old on May 23, 2019. That's pretty old for a programming language. The fact that it's still widely used and runs many of the world's largest organizations is pretty incredible. Java has a unique problem among languages in that it means two things: Java the language and Java the runtime.

Many developers think that Java is _old_ and therefore shouldn't be used. However, the most popular programming language today -- JavaScript -- was born less than six months after Java, on December 4, 1995. But I digress.

Java the runtime is often called the Java Virtual Machine, or JVM. Rarely do people complain about the runtime. Most developers are impressed by the JVM's features, and many Java alternative languages run on the JVM. Some of the most popular ones include Clojure, Groovy, JRuby, Kotlin, and Scala.

There's also confusion about the JDK (Java Development Kit) versus the JRE (Java Runtime Environment). The JDK is used by developers when they're writing and compiling Java code, the JRE is used to run Java application. End users shouldn't have to worry about this, yet it's a common problem that developers set their `JAVA_HOME` to point to the JRE location on their system.

I thought it'd be fun to write a post that dispels some of the most common myths about Java. I started by compiling my own list of myths, then asking Java developers I work with if they thought it was accurate. This worked, but I quickly realized this wasn't the information I was looking for. I was looking at myths about Java from the wrong perspective. I needed to get the perpectives of non-Java developers.

I asked the following in a company Slack room that has a lot of Java haters:

> For those with a negative opinion of Java, can you tell me why you don’t like it?

This question gave me the perspective I wanted! Now let's get on with trying to dispel the myths about Java in 2019.

Below is a list of reasons why my fellow developers have a negative opinion of Java. Below each section header, I've attempted a counter argument to explain that it's not true.

== 1. Java is heavy compared to interpreted languages like Python, Ruby, or JavaScript

I can see how this is a common opinion. If you tried Java anytime before 2014, chances are you had to jump through a lot of hoops to get things setup. You had to install a JDK, a build tool (or IDE), then configure your IDE or build tool to work. The getting started process was heavy.

In 2019, you can create a Spring Boot app with start.spring.io in seconds and the build tool is included in your download.

----
# install SDKMAN
curl -s "https://get.sdkman.io" | bash
# install JDK
sdk install java
# create app
curl https://start.spring.io/starter.zip -d dependencies=web -d javaVersion=11 -o demo.zip
# run it
cd demo && ./mvnw spring-boot:run
----

As far as the language is concerned, it is somewhat "high ceremony". Java 8 reduced a lot of complaints when it added lambdas. Some even say lambdas caused a reduction in Scala enthusiasm.

The major gripe I've seen from developers is you have to write getters and setters for POJOs. This will soon be elimated with https://dzone.com/articles/april-2019-update-on-java-records[Java Records]. You can eliminate this now using https://projectlombok.org/[Lombok].

Other than that, "heavy" can mean static typing. It can also mean heavy as in EJBs. To me, "Java is heavy" makes me think of Java EE, app servers, and EJBs. The Java I use these days feels very lightweight in that I wait less time for Spring Boot to compile/start than I do for my TypeScript to compile. However, it does seem to still be a concern - especially since super-fast startup times has become a trend; popularized by Micronaut and Quarkus. Even Spring Boot has https://www.youtube.com/watch?v=_m4xpHUf55E[been influenced by this movement].

As far as Java EE is concerned, that's over. Jakarta EE is the 🔥 new thing and MicroProfile is leading the charge to standardize Java microservice architectures that are cloud ready. MicroProfile even offers a way to https://microprofile.io/2019/07/08/command-line-interface-for-microprofile-starter-is-available-now/[create applications using the command line], much like Spring Boot.

**Is it true?** In the past, yes. Not in 2019.

== 2. Java is long-winded compared to C#

I had to ask for clarification on this one. The person responded, "I remember having to write longer "sentences" in Java". They also mentioned having to use fully qualified references inline.

This is typically not the fault of the language, but rather frameworks. After all, Spring Framework's https://gist.github.com/thom-nic/2c74ed4075569da0f80b[longest class] is 97 characters long!

----
HasThisTypePatternTriedToSneakInSomeGenericOrParameterizedTypePatternMatchingStuffAnywhereVisitor
----

It's nice to know what a class does by its name, but I agree that frameworks can be overly verbose. As a developer, you can use whatever names you like for your classes. Just link:/blog/2019/06/25/iinterface-considered-harmful[don't use an `I` prefix for your interfaces]. That convention died long ago.

Using fully qualified class names is only a problem when you have the same class name in different packages. I've only run into this a handful of times in projects I've worked on. Adding `import x as y` would solve this problem, but it's rarely an issue IMO.

**Is it true?** No. Java isn't long-winded. Some of its popular frameworks are.

== 3. Packaging and Dependency Management is Confusing

Now that I know the intricacies of Maven and Gradle, I think dependency management works quite well in Java. However, I do remember when I migrated AppFuse from Ant to Maven back in 2005. It took a full year and I had to go to the hospital for burnout at one point. Now that I'm recovered and Maven hasn't changed much in 10 years, I rarely think about how to use it.

I realize that people new to Java don't feel the same way. When they open a large `pom.xml` or `build.gradle` and they want to add a new dependency, they might not know where to add it. Especially if the project uses profiles and has multiple `<dependency>` blocks.

For Node projects, all you need is a `package.json` project and it's pretty straightforward. Want to add custom behavior? Just add some lines to the `script` block. Want to add a new dependency? Just run `npm i groupId/artifactId`.

TIP: I recommend using `npm i -E groupId/artifactId@version` to lock down the version number. Especially if you're writing tutorials.

I do think it would be cool if Maven and Gradle had something like `mvn add groupId/artifactId`.

I also think dependency resolution is much better in Java than in JavaScript. Maven and Gradle store artifacts in a single location instead of within each project. Also, the convention is Java projects is to lock down the version. JavaScript projects tend to use version ranges and people break semantic versions rules _all the time_. Maven supports version ranges too, but virtually no one uses them in Javaland.

As far as packaging goes, just create a JAR. Nothing else is really necessary. Make JAR, not WAR!

**Is it true?** Yes. Most Java developers will likely say dependency management is not confusing. However, because people feel like they have to learn Maven and Gradle, I think it is. No one has to learn how `package.json` works to be an effective Node developer. As for webpack, that's a whole different ballgame! 😅

== 4. The Preference of Objects over Primitives

Java supports primitives like `int` and `boolean`, and object types like `Integer` and `Boolean`. Primitives use less memory and are much faster. So why does Java recommend you use objects? I can think of a couple of reasons:

1. Primitives can't be `null` (the default value for `int` is `0`; `false` for `boolean`)
2. Primitives can't be used with generics

Baeldung has a good post on https://www.baeldung.com/java-primitives-vs-objects[Java Primitives versus Objects].

**Is it true?** Yes. We prefer objects over primitives for the reasons stated above. You can use lighter and faster primitives, but beware of the caveats.

== 5. Strong typing and the Diamond Operator sucks

There are many dynamic language aficionados that hate static typing. If you're not a fan of static typing, Java probably won't work for you. However, if you want to deploy apps on the JVM, you might like Groovy! It doesn't have static typing by default, but you can add it if you want it.

I'm not sure why the Diamond Operator sucks. Maybe because you need to type it? My IDE usually handles that code completion for me.

**Is it true?** Yes, Java requires strong typing. Large codebases usually benefit from it.

== 6. Java sucks because it relies on XML for framework config vs JSON

In the days of J2EE, EJB, and early Spring versions, this was true. However, the default config files for Java apps tend to be properties files, which are tough to mess up. I've rarely misconfigured up a properties file; I can't say the same thing for JSON or YAML.

XML does have schemas, and JSON has copied that with https://json-schema.org/[JSON Schema]. Maybe they've discovered that developers like code completion?

**Is it true?** No. Not in 2019.

== 7. You need to carefully craft/tweak your IDE to get the basics

You have to install a JDK, install your IDE, point your IDE to the correct JDK, etc. The person that had this opinion also stated they think Java IDEs are heavy.

If installing a JDK is a pain for you, use SDKMAN! Same goes for managing your `JAVA_HOME` environment variable. SDKMAN has extracted this problem away for me and it's no longer a concern.

It's true that if you have more than one JDK installed, you will have to configure your IDE to point to it. I think you'd have the same problem with Node, Ruby, or .NET. This is not a Java-specific problem.

What about Java IDEs? I agree they're heavy. When I first started programming in Java (in the late 90s), I used HomeSite because I found it fast to startup and lightweight to use. I didn't use an IDE until Eclipse came along. It was the first one that was fast enough to be tolerable. These days, I use TextMate and VS Code when I need a lightweight editor.

**Is it true?** If you only have one JDK installed, I don't think so. Otherwise, yes.

NOTE: I find it funny that VS Code is often considered lightweight. Yet it's based on Electron, which is viewed as heavy. Maybe that's all Slack's fault?

== 8. JAVA_HOME and all the other environment variables are really confusing

Defining `JAVA_HOME` can be required, but not if you use SDKMAN. I ran `export JAVA_HOME=` and was able to run Maven and Gradle just fine.

**Is it true?** Yep. Don't use `JAVA_HOME`.

== 9. Java is stupidly complex without an IDE

**Stupidly complex** are strong words. When using HomeSite to write Java, I had to look up package names and manually add the imports. With an IDE, the import happens automatically. With an IDE, code completion happens. With an IDE, I'm prompted to refactor code and make it simpler. Even when writing JavaScript and TypeScript, I prefer an IDE for the auto-imports and code completion.

**Is it true?** Yes. I think development in general is complex without an IDE. IDEs can save you thousands of keystrokes in a day and are tremendously helpful when refactoring.

== 10. Java Licensing is Confusing

I think most Java developers will agree that licensing has been a confusing topic recently. Especially since the JDK became OpenJDK and there's so many different distributions.

The funny thing about this particular point is no non-Java developers mentioned it. Even though we as Java developers think it's confusing, no one outside of the Java community is really concerned. Maybe it's because they're no longer interested in Java.

**Is it true?** No. Java licensing is not confusing. If you like to download and install a JDK, use https://adoptopenjdk.net/[AdoptOpenJDK]. If you'd rather use something that automates installing Java and switching Java versions, use https://sdkman.io/[SDKMAN!] For more info on this subject, see link:/blog/2019/01/16/which-java-sdk[Which Java SDK Should You Use?]

== Java vs JavaScript

In my experience, most of the people that hate Java these days are JavaScript developers. They love the dynamic nature of JavaScript and how it can now be used on the client and server. Personally, I love the JavaScript on the front end and Java on the backend combination. I also think it's quite amusing that this was the vision for JavaScript from day 1, when it was https://web.archive.org/web/20070916144913/http://wp.netscape.com/newsref/pr/newsrelease67.html[first announced]:

> 28 INDUSTRY-LEADING COMPANIES TO ENDORSE JAVASCRIPT AS A COMPLEMENT TO JAVA FOR EASY ONLINE APPLICATION DEVELOPMENT

**Do you recommend using them together?** Yes. JavaScript + Java is like peanut butter jelly. See https://www.jhipster.tech/[JHipster].

== Learn More about Java and JavaScript

We're big fans of Java, JavaScript, and many other languages here at Okta. There are huge fans of Ruby, Python, C#, Goovy, and Kotlin in our midst. On this blog, we tend to write about the most popular languages for a wider reach, but we're also curious developers. We like to learn new things and and try to keep an open mind.

Have some additional myths about Java you'd like to refute? Please provide feedback in the comments.

If you'd like to read some tutorials about using Java and JavaScript, check out these links:

* link:/blog/2019/06/24/ionic-4-angular-spring-boot-jhipster[Build Mobile Apps with Angular, Ionic 4, and Spring Boot]
* link:/blog/2019/06/18/command-line-app-with-nodejs[Build a Command Line Application with Node.js]
* link:/blog/2019/05/22/java-microservices-spring-boot-spring-cloud[Java Microservices with Spring Boot and Spring Cloud]

For more fun tech talk, follow us https://twitter.com/oktadev[@oktadev] on Twitter or subscribe to https://www.youtube.com/c/oktadev[our YouTube channel].
